
languageCode = "en-us"


theme = "zafta"
baseurl = "http://aheitzen.github.io/alexaheitzblog" 
canonifyurls = true 
pluralizelisttitles = false

contentdir = "content"
layoutsdir = "layouts"
publishdir = "public"

title = "Title of your blog"
MetaDataFormat = "toml"
pygmentsuseclasses = true 



[permalinks]
fixed = ":title/"
blog = ":slug/" 