
languageCode = "en-us"



baseurl = "http://aheitzen.github.io/alexaheitzblog" 
canonifyurls = true 
pluralizelisttitles = false

contentdir = "content"
layoutsdir = "layouts"
publishdir = "public"

title = "Title of your blog"
pygmentsuseclasses = true 

[permalinks]
fixed = ":title/"
blog = ":slug/" 